image: ubuntu:16.04

stages:
  - build
  - prepare
  - test
  - deploy


variables:
  MYSQL_DATABASE: "TestDB"
  MYSQL_ROOT_PASSWORD: "1q2w3e4r"


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apt-get update && apt-get install -y gnupg2
  - apt-key adv --recv-keys --keyserver keyserver.ubuntu.com AA8E81B4331F7F50
  - apt-get install -qq git
  - 'which ssh-agent || ( apt install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


build:
  stage: build
  image: gradle
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle


prepare:
  stage: prepare
  image: java:openjdk-8
  services:
    - mariadb
  script:
    - apt-get update && apt-get --assume-yes install mysql-client -y -qq
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mariadb < "data/create_db.sql"

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

deploy:
  stage: deploy
  script:
    - ssh root@192.168.10.150 "systemctl restart Auction_Service"
    - ssh root@5.253.24.159 "systemctl restart Auction_Service"
