package com.rahnemacollege.util.exceptions;

public enum Message{
    TITLE_NULL,
    TITLE_TOO_LONG,
    DESCRIPTION_TOO_LONG,
    BASE_PRICE_NULL,
    CATEGORY_NULL,
    CATEGORY_INVALID,
    DATE_NULL,
    MAX_NUMBER_TOO_LOW,
    MAX_NUMBER_TOO_HIGH,
    DATE_INVALID,
    MAX_SIZE_EXCEEDED,

    EMAIL_INVALID,
    PASSWORD_TOO_LOW,
    PASSWORD_TOO_HIGH,
    NAME_NULL,
    EMAIL_NULL,
    EMAIL_DUPLICATED,

    PASSWORD_INCORRECT,
    EMAIL_INCORRECT,

    EMAIL_NOT_FOUND,
    INVALID_RESET_LINK,
    TOKEN_NOT_FOUND,
    NOT_RECORDED_REQUEST,

    INVALID_ID,
    AUCTION_NOT_FOUND,
    REALLY_BAD_SITUATION


}

