/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rahnemacollege;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

import java.util.Date;


@SpringBootApplication(exclude = {JacksonAutoConfiguration.class}, scanBasePackages={
        "com.rahnemacollege"})
@EnableJpaRepositories("com.rahnemacollege.repository")
public class App extends SpringBootServletInitializer {

    public static void main(String[] args)
    {
        System.err.println(new Date());
        SpringApplication.run(App.class, args);
    }
}
