/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rahnemacollege;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

//@SpringBootApplication(exclude = {JacksonAutoConfiguration.class})
@Configuration @EnableAutoConfiguration @ComponentScan
public class App implements CommandLineRunner {

    public static void main(String[] args)
    {
        SpringApplication.run(App.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
        //TODO: add category to DB
    }
}
