/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rahnemacollege;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
<<<<<<< HEAD
=======
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();

    }
>>>>>>> e3756a553c02d4b0ede59c80e2c46ed3c32f3280
}
