ALTER DATABASE AuctionProjectDB CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE Auctions CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE auctions CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE Users CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE users CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE Bids CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE bids CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE Categories CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE categories CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
